<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Add foreign key column
        Schema::table('employees', function (Blueprint $table) {
            if (!Schema::hasColumn('employees', 'designation_id')) {
                $table->foreignId('designation_id')
                    ->nullable()
                    ->after('designation')
                    ->constrained('designations')
                    ->nullOnDelete();
            }
        });

        // 2. Data Migration
        if (Schema::hasColumn('employees', 'designation')) {
            // Select distinct existing designations
            $existingDesignations = DB::table('employees')
                ->whereNotNull('designation')
                ->where('designation', '!=', '')
                ->distinct()
                ->pluck('designation');

            foreach ($existingDesignations as $desName) {
                $desName = trim($desName);
                if (empty($desName)) continue;

                // Find or Create in designations table
                $designation = DB::table('designations')->where('name', $desName)->first();
                
                if (!$designation) {
                    $id = DB::table('designations')->insertGetId([
                        'name' => $desName,
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now(),
                    ]);
                    $designationId = $id;
                } else {
                    $designationId = $designation->id;
                }

                // 3. Map employees
                DB::table('employees')
                    ->where('designation', $desName)
                    ->update(['designation_id' => $designationId]);
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('employees', function (Blueprint $table) {
            if (Schema::hasColumn('employees', 'designation_id')) {
                // Determine the foreign key name automatically generated by Laravel
                // Typically employees_designation_id_foreign
                $table->dropForeign(['designation_id']);
                $table->dropColumn('designation_id');
            }
        });
    }
};
